/**
 * OMRANCO BURGER real menu — sourced from the restaurant printed menu.
 * Replace later with API/Firebase; keep these shapes as the UI contract.
 *
 * Types/constants live in menu-types / menu-constants so CartProvider does not
 * pull this module (and its product images) into the initial client chunk.
 */

import burgerImg from "@/assets/item-burger.jpg";
import chickenImg from "@/assets/item-chicken.jpg";
import sandwichImg from "@/assets/item-sandwich.jpg";
import mealImg from "@/assets/item-meal.jpg";
import friesImg from "@/assets/item-fries.jpg";
import drinkImg from "@/assets/item-drink.jpg";
import sticksBurgerImg from "@/assets/sticks-burger.png";

export type {
  Branch,
  Category,
  CategoryId,
  Offer,
  OptionChoice,
  OptionGroup,
  Product,
} from "@/lib/menu-types";
import type { Branch, Category, Offer, Product } from "@/lib/menu-types";

export { CURRENCY, DELIVERY_FEE, deliveryZones } from "@/lib/menu-constants";

export const categories: Category[] = [
  { id: "beef", nameAr: "برجر لحم", nameEn: "Beef Burger", image: burgerImg },
  { id: "chicken", nameAr: "برجر تشيكن", nameEn: "Chicken Burger", image: chickenImg },
  { id: "appetizers", nameAr: "مقبلات", nameEn: "Appetizers", image: friesImg },
  { id: "new", nameAr: "الجديد", nameEn: "New Items", image: mealImg },
  { id: "mix", nameAr: "مكس", nameEn: "Mix", image: sandwichImg },
  { id: "combo", nameAr: "كومبو", nameEn: "Combo", image: drinkImg },
  { id: "extras", nameAr: "إضافات", nameEn: "Extras", image: friesImg },
  { id: "kids", nameAr: "وجبات أطفال", nameEn: "Kids Meals", image: mealImg },
];

/** Beef menu uses Single (S) as base price; Double (D) is an add-on. */
function beefSize(single: number, double: number): OptionGroup {
  return {
    id: "size",
    nameAr: "الحجم",
    nameEn: "Size",
    type: "single",
    required: true,
    choices: [
      { id: "single", nameAr: "سنجل (S)", nameEn: "Single (S)", price: 0 },
      {
        id: "double",
        nameAr: "دوبل (D)",
        nameEn: "Double (D)",
        price: double - single,
      },
    ],
  };
}

const sauceExtras: OptionGroup = {
  id: "extras",
  nameAr: "إضافات",
  nameEn: "Extras",
  type: "multi",
  choices: [
    { id: "coleslaw", nameAr: "كول سلو", nameEn: "Coleslaw", price: 25 },
    { id: "cheddar", nameAr: "شيدر", nameEn: "Cheddar", price: 20 },
    { id: "ranch", nameAr: "رانش", nameEn: "Ranch", price: 20 },
    { id: "texas-hot", nameAr: "تكساس حار", nameEn: "Texas Hot", price: 20 },
    { id: "texas", nameAr: "تكساس عادي", nameEn: "Texas", price: 20 },
    { id: "sweet-chili", nameAr: "سويت شيلي", nameEn: "Sweet Chili", price: 20 },
    { id: "mayo", nameAr: "مايونيز", nameEn: "Mayonnaise", price: 20 },
    { id: "thousand", nameAr: "1000 جزيرة", nameEn: "1000 Island", price: 20 },
  ],
};

export const products: Product[] = [
  // ─── BEEF BURGER (printed BEEF menu) ───────────────────────────
  {
    id: "beef-ya-omry",
    categoryId: "beef",
    nameAr: "يا عمري برجر",
    nameEn: "Ya Omri Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام من اللحم البلدي الصافي + الجبنة الكريمي + صوص الرانش + المشروم الطازج + البصل المكرمل + الخيار المخلل.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, cream cheese, ranch sauce, fresh mushrooms, caramelized onions, and pickles.",
    price: 155,
    image: burgerImg,
    available: true,
    popular: true,
    optionGroups: [beefSize(155, 230), sauceExtras],
  },
  {
    id: "beef-omranco",
    categoryId: "beef",
    nameAr: "عمرانكو برجر",
    nameEn: "Omranco Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام من اللحم البلدي الصافي + صوص الشيدر + صوص التكساس + الخس + البصل المكرمل + الخيار المخلل.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, cheddar sauce, Texas sauce, lettuce, caramelized onions, and pickles.",
    price: 160,
    image: burgerImg,
    available: true,
    popular: true,
    optionGroups: [beefSize(160, 235), sauceExtras],
  },
  {
    id: "beef-classic",
    categoryId: "beef",
    nameAr: "كلاسيك برجر",
    nameEn: "Classic Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام لحم بلدي صافي + الطماطم المشوية + البصل المشوي + الخس + الخيار المخلل + صوص الألف جزيرة + صوص الشيدر.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, grilled tomatoes, grilled onions, lettuce, pickles, Thousand Island sauce, and cheddar sauce.",
    price: 145,
    image: burgerImg,
    available: true,
    popular: true,
    optionGroups: [beefSize(145, 220), sauceExtras],
  },
  {
    id: "beef-ya-weily",
    categoryId: "beef",
    nameAr: "يا ويلي برجر",
    nameEn: "Ya Weely Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام لحم بلدي صافي + الخس + الخيار المخلل + صوص السويت شيلي + الصوص الحار + قطع الهالبينو + صوص الشيدر.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, lettuce, pickles, sweet chili sauce, hot sauce, jalapeños, and cheddar sauce.",
    price: 160,
    image: burgerImg,
    available: true,
    optionGroups: [beefSize(160, 235), sauceExtras],
  },
  {
    id: "beef-onion",
    categoryId: "beef",
    nameAr: "أونيونبيف برجر",
    nameEn: "Onionbeef Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام من اللحم البلدي الصافي + صوص الشيدر + صوص الباربيكيو + حلقات البصل المقلية + الخيار المخلل + الخس + المايونيز.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, cheddar sauce, BBQ sauce, fried onion rings, pickles, lettuce, and mayonnaise.",
    price: 165,
    image: burgerImg,
    available: true,
    optionGroups: [beefSize(165, 240), sauceExtras],
  },
  {
    id: "beef-sticks",
    categoryId: "beef",
    nameAr: "ستيكس برجر",
    nameEn: "Sticks Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام من اللحم البلدي الصافي + صوص الشيدر + اصابع الموتزاريلا المقلية + صوص الرانش + الخيار المخلل + الخس + المايونيز.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, cheddar sauce, fried mozzarella sticks, ranch sauce, pickles, lettuce, and mayonnaise.",
    price: 175,
    image: sticksBurgerImg,
    available: true,
    popular: true,
    optionGroups: [beefSize(175, 250), sauceExtras],
  },
  {
    id: "beef-infinity",
    categoryId: "beef",
    nameAr: "انفينيتي برجر",
    nameEn: "Infinity Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام من اللحم البلدي الصافي + صوص الشيدر + بيف بيكون + مشروم طازج + صوص الباربيكيو + الخيار المخلل + الخس + المايونيز.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, cheddar sauce, beef bacon, fresh mushrooms, BBQ sauce, pickles, lettuce, and mayonnaise.",
    price: 170,
    image: burgerImg,
    available: true,
    popular: true,
    optionGroups: [beefSize(170, 245), sauceExtras],
  },
  {
    id: "beef-hotdog",
    categoryId: "beef",
    nameAr: "هوت دوج برجر",
    nameEn: "Hot Dog Burger",
    descAr:
      "عيش كايزر + ١٥٠ جرام من اللحم البلدي الصافي + صوص الشيدر + هوت دوج + طماطم مشوية + بصل + كاتشب + الخيار المخلل + الخس + المايونيز.",
    descEn:
      "Kaiser bun, 150g pure baladi beef, cheddar sauce, hot dog, grilled tomatoes, onions, ketchup, pickles, lettuce, and mayonnaise.",
    price: 170,
    image: burgerImg,
    available: true,
    optionGroups: [beefSize(170, 245), sauceExtras],
  },
  {
    id: "beef-texas-wrap",
    categoryId: "beef",
    nameAr: "تكساس بيف راب",
    nameEn: "Texas Beef Wrap",
    descAr:
      "عيش تورتيلا + ٧٥ جرام من اللحم البلدي الصافي المفروم + جبن موتزاريلا + طماطم مشوية + بصل مشوي على الجريل + الخيار المخلل + الخس.",
    descEn:
      "Tortilla, 75g minced pure baladi beef, mozzarella cheese, grilled tomatoes, grilled onions, pickles, and lettuce.",
    price: 110,
    image: sandwichImg,
    available: true,
  },
  {
    id: "beef-texas-wrap-extra",
    categoryId: "beef",
    nameAr: "تكساس بيف راب إكسترا حشو",
    nameEn: "Texas Beef Wrap Extra Filling",
    descAr:
      "عيش تورتيلا + ١٥٠ جرام من اللحم البلدي الصافي المفروم + جبن موتزاريلا + طماطم مشوية + بصل مشوي على الجريل + الخيار المخلل + الخس.",
    descEn:
      "Tortilla, 150g minced pure baladi beef, mozzarella cheese, grilled tomatoes, grilled onions, pickles, and lettuce.",
    price: 155,
    image: sandwichImg,
    available: true,
  },
  {
    id: "beef-ya-lahwy",
    categoryId: "beef",
    nameAr: "يا لهوي",
    nameEn: "Ya Lahwy",
    descAr:
      "عيش تورتيلا + برجر مع صوص التكساس + بصل مكرمل + دجاج جريلد مع صوص الباربيكيو + دجاج مقلي مع صوص السويت شيلي + صوص الشيدر الملفوفة رول والمقلية بطبقة الكورن + صوص الألف جزيرة + الخيار المخلل + الخس.",
    descEn:
      "Tortilla with Texas-sauced burger, caramelized onions, BBQ grilled chicken, sweet-chili fried chicken, cheddar corn-coated fried roll, Thousand Island, pickles, and lettuce.",
    price: 210,
    image: sandwichImg,
    available: true,
    popular: true,
  },

  // ─── CHICKEN BURGER (printed CHICKENS menu) ────────────────────
  {
    id: "chk-coleslaw",
    categoryId: "chicken",
    nameAr: "كول سلو تشيكن",
    nameEn: "Coleslaw Chicken",
    descAr:
      "عيش كايزر + قطعتين صدور دجاج مقلي بتتبيلتنا الخاصة + صوص شيدر + كول سلو + خس + مايونيز.",
    descEn:
      "Kaiser bun, 2 fried chicken breast pieces with special seasoning, cheddar sauce, coleslaw, lettuce, and mayonnaise.",
    price: 160,
    image: chickenImg,
    available: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-grilled-kaiser",
    categoryId: "chicken",
    nameAr: "جريلد تشيكن كايزر",
    nameEn: "Grilled Chicken Kaiser",
    descAr:
      "عيش كايزر + قطعتين صدور دجاج مشوي بتتبيلتنا الخاصة + صوص شيدر + بيف بيكون + مشروم + باربيكيو + خس + مايونيز.",
    descEn:
      "Kaiser bun, 2 grilled chicken breast pieces with special seasoning, cheddar sauce, beef bacon, mushrooms, BBQ sauce, lettuce, and mayonnaise.",
    price: 160,
    image: chickenImg,
    available: true,
    popular: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-mexican-grilled",
    categoryId: "chicken",
    nameAr: "مكسيكان تشيكن جريلد",
    nameEn: "Mexican Chicken Grilled",
    descAr:
      "عيش فينو + قطعتين دجاج جريلد + بصل مكرمل + هاليبينو + صوص شيدر + جبنة موزاريلا + مايونيز + خس.",
    descEn:
      "Fino bread, 2 grilled chicken pieces, caramelized onions, jalapeños, cheddar sauce, mozzarella cheese, mayonnaise, and lettuce.",
    price: 160,
    image: chickenImg,
    available: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-cheese-mushroom",
    categoryId: "chicken",
    nameAr: "جريلد تشيكن تشيز اند مشروم",
    nameEn: "Grilled Chicken Cheese and Mushroom",
    descAr:
      "عيش فينو + قطعتين دجاج جريلد + بصل مكرمل + جبنة موزاريلا + مايونيز + خس + خيار مخلل + صوص شيدر.",
    descEn:
      "Fino bread, 2 grilled chicken pieces, caramelized onions, mozzarella cheese, mayonnaise, lettuce, pickles, and cheddar sauce.",
    price: 165,
    image: chickenImg,
    available: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-country-wrap",
    categoryId: "chicken",
    nameAr: "كانتري تشيكن راب",
    nameEn: "Country Chicken Wrap",
    descAr:
      "عيش تورتيلا + قطعتين صدور دجاج مقلي + صوص تكساس + جبنة موزاريلا + خس + خيار مخلل + صوص ثاوزند آيلاند.",
    descEn:
      "Tortilla bread, 2 fried chicken breast pieces, Texas sauce, mozzarella cheese, lettuce, pickles, and Thousand Island sauce.",
    price: 135,
    image: sandwichImg,
    available: true,
  },
  {
    id: "chk-fajita-wrap",
    categoryId: "chicken",
    nameAr: "تشيكن فاهيتا راب",
    nameEn: "Chicken Fajita Wrap",
    descAr:
      "عيش تورتيلا + قطعتين صدور دجاج جريلد + بصل مكرمل + فلفل ألوان + مشروم + جبنة موزاريلا.",
    descEn:
      "Tortilla bread, 2 grilled chicken breast pieces, caramelized onions, bell peppers, mushrooms, and mozzarella cheese.",
    price: 140,
    image: sandwichImg,
    available: true,
  },
  {
    id: "chk-cordon-kaiser",
    categoryId: "chicken",
    nameAr: "نيو كوردينيو كايزر",
    nameEn: "New Cordenio Kaiser",
    descAr:
      "عيش كايزر + قطعة دجاج مقلي محشي أجبان خاصة + رومي مدخن + بيف بيكون + خس + مايونيز.",
    descEn:
      "Kaiser bun, fried chicken piece stuffed with special cheeses, smoked turkey, beef bacon, lettuce, and mayonnaise.",
    price: 160,
    image: chickenImg,
    available: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-cordon-amo",
    categoryId: "chicken",
    nameAr: "كوردينيو عمو وليد",
    nameEn: "Cordenio Ammo Walid",
    descAr:
      "عيش فينو + رول دجاج مقلي محشي أجبان خاصة + بيكون + رومي مدخن + صوص شيدر + رانش + تكساس + خس + مايونيز.",
    descEn:
      "Fino bread, fried chicken roll stuffed with special cheeses, bacon, smoked turkey, cheddar sauce, ranch sauce, Texas sauce, lettuce, and mayonnaise.",
    price: 165,
    image: chickenImg,
    available: true,
    popular: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-new",
    categoryId: "chicken",
    nameAr: "نيو تشيكن",
    nameEn: "New Chicken",
    descAr: "عيش فينو + قطع دجاج جريلد + طماطم + بصل مشوي + جبنة موزاريلا + كريمة.",
    descEn:
      "Fino bread, grilled chicken pieces, tomatoes, grilled onions, mozzarella cheese, and cream.",
    price: 160,
    image: chickenImg,
    available: true,
  },
  {
    id: "chk-classic",
    categoryId: "chicken",
    nameAr: "كلاسيك تشيكن برجر",
    nameEn: "Classic Chicken Burger",
    descAr: "عيش كايزر + برجر دجاج جريلد + مايونيز + صوص شيدر + صوص تكساس + خس.",
    descEn:
      "Kaiser bun, grilled chicken burger patty, mayonnaise, cheddar sauce, Texas sauce, and lettuce.",
    price: 140,
    image: chickenImg,
    available: true,
    popular: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-mexican-burger",
    categoryId: "chicken",
    nameAr: "مكسيكان تشيكن برجر",
    nameEn: "Mexican Chicken Burger",
    descAr:
      "عيش كايزر + برجر دجاج جريلد + مايونيز + خيار مخلل + بصل مكرمل + هاليبينو + صوص شيدر + جبنة موزاريلا.",
    descEn:
      "Kaiser bun, grilled chicken burger patty, mayonnaise, pickles, caramelized onions, jalapeños, cheddar sauce, and mozzarella cheese.",
    price: 150,
    image: chickenImg,
    available: true,
    optionGroups: [sauceExtras],
  },
  {
    id: "chk-ranch",
    categoryId: "chicken",
    nameAr: "تشيكن رانش",
    nameEn: "Chicken Ranch",
    descAr:
      "عيش كايزر + قطعتين صدور دجاج مقلي + صوص شيدر + رومي مدخن + رانش + خس + مايونيز.",
    descEn:
      "Kaiser bun, 2 fried chicken breast pieces, cheddar sauce, smoked turkey, ranch sauce, lettuce, and mayonnaise.",
    price: 160,
    image: chickenImg,
    available: true,
    popular: true,
    optionGroups: [sauceExtras],
  },

  // ─── APPETIZERS ────────────────────────────────────────────────
  {
    id: "app-new-fries-chicken",
    categoryId: "appetizers",
    nameAr: "نيو فرايز تشيكن",
    nameEn: "New Fries Chicken",
    descAr: "بطاطس + قطع تشيكن + جبنة + كريمة + طماطم + بصل + هالبينو + صوص تكساس.",
    descEn: "Fries, chicken pieces, cheese, cream, tomato, onion, jalapeño, and Texas sauce.",
    price: 155,
    image: friesImg,
    available: true,
    popular: true,
  },
  {
    id: "app-crunchy-start",
    categoryId: "appetizers",
    nameAr: "كرانشي استارت",
    nameEn: "Crunchy Start",
    descAr: "٣ قطع تشيكن فينجرز + رانش + كول سلو + هاني مسترد.",
    descEn: "3 chicken fingers, ranch, coleslaw, and honey mustard.",
    price: 150,
    image: chickenImg,
    available: true,
  },
  {
    id: "app-mozzarella",
    categoryId: "appetizers",
    nameAr: "موتزاريلا ستيكس",
    nameEn: "Mozzarella Sticks",
    descAr: "٣ قطع مع سويت شيلي.",
    descEn: "3 sticks with sweet chili.",
    price: 55,
    image: friesImg,
    available: true,
  },
  {
    id: "app-onion-rings",
    categoryId: "appetizers",
    nameAr: "اونيون رينجز",
    nameEn: "Onion Rings",
    descAr: "٦ قطع مع سويت شيلي.",
    descEn: "6 pieces with sweet chili.",
    price: 55,
    image: friesImg,
    available: true,
  },
  {
    id: "app-omranco-fries",
    categoryId: "appetizers",
    nameAr: "بطاطس عمرانكو",
    nameEn: "Omranco Fries",
    descAr: "بطاطس كبيرة + جبنة + لحم قلب + مخلل حار.",
    descEn: "Large fries, cheese, heart meat, and chili pickles.",
    price: 90,
    image: friesImg,
    available: true,
    popular: true,
  },
  {
    id: "app-texas-beef",
    categoryId: "appetizers",
    nameAr: "تكساس بيف",
    nameEn: "Texas Beef",
    descAr: "بطاطس + بيف حار + صوص تكساس + هالبينو + طماطم + بصل + كريمة (عادي / حار).",
    descEn: "Fries, chili beef, Texas sauce, jalapeño, tomato, onion, and cream (regular / hot).",
    price: 155,
    image: burgerImg,
    available: true,
  },
  {
    id: "app-texas-chicken",
    categoryId: "appetizers",
    nameAr: "تكساس تشيكن",
    nameEn: "Texas Chicken",
    descAr: "بطاطس + تشيكن + صوص تكساس + رانش + هالبينو.",
    descEn: "Fries, chicken, Texas sauce, ranch, and jalapeño.",
    price: 155,
    image: chickenImg,
    available: true,
  },
  {
    id: "app-texas-smoked",
    categoryId: "appetizers",
    nameAr: "تكساس سمووكد",
    nameEn: "Texas Smoked",
    descAr: "بطاطس + لحوم مدخنة + صوص تكساس + باربيكيو + بصل مدخن + طماطم + هالبينو.",
    descEn: "Fries, smoked meat, Texas sauce, BBQ, smoked onion, tomato, and jalapeño.",
    price: 155,
    image: sandwichImg,
    available: true,
  },
  {
    id: "app-texas-hotdog",
    categoryId: "appetizers",
    nameAr: "تكساس هوت دوج",
    nameEn: "Texas Hot Dog",
    descAr: "بطاطس + هوت دوج + بصل + طماطم + صوص شيدر.",
    descEn: "Fries, hot dog, onion, tomato, and cheddar sauce.",
    price: 125,
    image: sandwichImg,
    available: true,
  },

  // ─── NEW ITEMS ─────────────────────────────────────────────────
  {
    id: "new-pasta-burger",
    categoryId: "new",
    nameAr: "باستا برجر",
    nameEn: "Pasta Burger",
    descAr: "باستا برجر — جرب الجديد.",
    descEn: "Pasta burger — try what's new.",
    price: 150,
    image: mealImg,
    available: true,
    popular: true,
  },
  {
    id: "new-chicken-tandoori",
    categoryId: "new",
    nameAr: "تشيكن تندوري",
    nameEn: "Chicken Tandoori",
    descAr: "تشيكن تندوري.",
    descEn: "Chicken tandoori.",
    price: 140,
    image: chickenImg,
    available: true,
  },
  {
    id: "new-cheese-steak",
    categoryId: "new",
    nameAr: "فيليه تشيز ستيك",
    nameEn: "Philly Cheese Steak",
    descAr: "فيليه تشيز ستيك.",
    descEn: "Philly cheese steak.",
    price: 150,
    image: sandwichImg,
    available: true,
  },
  {
    id: "new-quesadilla",
    categoryId: "new",
    nameAr: "كاسديا فاهيتا دجاج",
    nameEn: "Chicken Fajita Quesadilla",
    descAr: "كاسديا فاهيتا دجاج.",
    descEn: "Chicken fajita quesadilla.",
    price: 140,
    image: sandwichImg,
    available: true,
  },
  {
    id: "new-sweet-corn",
    categoryId: "new",
    nameAr: "سويت كورن",
    nameEn: "Sweet Corn",
    descAr: "سويت كورن.",
    descEn: "Sweet corn.",
    price: 70,
    image: friesImg,
    available: true,
  },
  {
    id: "new-cheese-jalapeno",
    categoryId: "new",
    nameAr: "تشيز هالبينو ٥ قطع",
    nameEn: "Cheese Jalapeño 5 pcs",
    descAr: "تشيز هالبينو ٥ قطع.",
    descEn: "Cheese jalapeño — 5 pieces.",
    price: 65,
    image: friesImg,
    available: true,
  },

  // ─── MIX ───────────────────────────────────────────────────────
  {
    id: "mix-ya-lahooy",
    categoryId: "mix",
    nameAr: "بالهوووي",
    nameEn: "Balhooooy",
    descAr: "برجر عملاق + ٤ ستربس + رانش + جبنة + هالبينو + كول سلو + عيش + بطاطس.",
    descEn: "Giant burger, 4 strips, ranch, cheese, jalapeño, coleslaw, bread, and fries.",
    price: 220,
    image: mealImg,
    available: true,
    popular: true,
  },
  {
    id: "mix-ya-hayaty",
    categoryId: "mix",
    nameAr: "يا حياتي",
    nameEn: "Ya Hayati",
    descAr: "قطعتين برجر (٢٠٠ جم) + قطعة تشيكن (١٢٠ جم) + رانش + باربيكيو + خس + طماطم + بصل + بطاطس + عيش.",
    descEn: "2 burger patties (200g), chicken piece (120g), ranch, BBQ, lettuce, tomato, onion, fries, and bread.",
    price: 195,
    image: mealImg,
    available: true,
  },
  {
    id: "mix-sogok",
    categoryId: "mix",
    nameAr: "سجق برجر",
    nameEn: "Sausage Burger",
    descAr: "سجق برجر.",
    descEn: "Sausage burger.",
    price: 200,
    image: burgerImg,
    available: true,
  },
  {
    id: "mix-omranco",
    categoryId: "mix",
    nameAr: "عمرانكو مكس",
    nameEn: "Omranco Mix",
    descAr: "عمرانكو مكس.",
    descEn: "Omranco mix.",
    price: 210,
    image: mealImg,
    available: true,
    popular: true,
  },

  // ─── COMBO ─────────────────────────────────────────────────────
  {
    id: "combo-meal",
    categoryId: "combo",
    nameAr: "كومبو",
    nameEn: "Combo",
    descAr: "بطاطس ٢٠٠ جم + مشروب.",
    descEn: "200g fries + drink.",
    price: 45,
    image: mealImg,
    available: true,
  },
  {
    id: "combo-fries-s",
    categoryId: "combo",
    nameAr: "بطاطس صغيرة",
    nameEn: "Small Fries",
    descAr: "بطاطس صغيرة.",
    descEn: "Small fries.",
    price: 30,
    image: friesImg,
    available: true,
  },
  {
    id: "combo-fries-l",
    categoryId: "combo",
    nameAr: "بطاطس كبيرة",
    nameEn: "Large Fries",
    descAr: "بطاطس كبيرة.",
    descEn: "Large fries.",
    price: 40,
    image: friesImg,
    available: true,
  },
  {
    id: "combo-cola",
    categoryId: "combo",
    nameAr: "بي ب كولا",
    nameEn: "B Cola",
    descAr: "بي ب كولا.",
    descEn: "B Cola.",
    price: 25,
    image: drinkImg,
    available: true,
  },
  {
    id: "combo-maxi",
    categoryId: "combo",
    nameAr: "ماكسي ب",
    nameEn: "Maxi B",
    descAr: "ماكسي ب.",
    descEn: "Maxi B drink.",
    price: 20,
    image: drinkImg,
    available: true,
  },
  {
    id: "combo-big-cola-s",
    categoryId: "combo",
    nameAr: "بيج كولا صغير",
    nameEn: "Big Cola Small",
    descAr: "بيج كولا صغير.",
    descEn: "Small Big Cola.",
    price: 15,
    image: drinkImg,
    available: true,
  },
  {
    id: "combo-juice",
    categoryId: "combo",
    nameAr: "عصير",
    nameEn: "Juice",
    descAr: "عصير.",
    descEn: "Juice.",
    price: 15,
    image: drinkImg,
    available: true,
  },
  {
    id: "combo-water",
    categoryId: "combo",
    nameAr: "مياه صغيرة",
    nameEn: "Small Water",
    descAr: "مياه صغيرة.",
    descEn: "Small water.",
    price: 10,
    image: drinkImg,
    available: true,
  },

  // ─── EXTRAS ────────────────────────────────────────────────────
  {
    id: "ex-coleslaw",
    categoryId: "extras",
    nameAr: "كول سلو",
    nameEn: "Coleslaw",
    descAr: "إضافة كول سلو.",
    descEn: "Coleslaw side.",
    price: 25,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-cheddar",
    categoryId: "extras",
    nameAr: "شيدر",
    nameEn: "Cheddar",
    descAr: "صوص شيدر.",
    descEn: "Cheddar sauce.",
    price: 20,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-ranch",
    categoryId: "extras",
    nameAr: "رانش",
    nameEn: "Ranch",
    descAr: "صوص رانش.",
    descEn: "Ranch sauce.",
    price: 20,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-texas-hot",
    categoryId: "extras",
    nameAr: "تكساس حار",
    nameEn: "Texas Hot",
    descAr: "صوص تكساس حار.",
    descEn: "Hot Texas sauce.",
    price: 20,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-texas",
    categoryId: "extras",
    nameAr: "تكساس عادي",
    nameEn: "Texas",
    descAr: "صوص تكساس.",
    descEn: "Texas sauce.",
    price: 20,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-sweet-chili",
    categoryId: "extras",
    nameAr: "سويت شيلي",
    nameEn: "Sweet Chili",
    descAr: "صوص سويت شيلي.",
    descEn: "Sweet chili sauce.",
    price: 20,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-mayo",
    categoryId: "extras",
    nameAr: "مايونيز",
    nameEn: "Mayonnaise",
    descAr: "مايونيز.",
    descEn: "Mayonnaise.",
    price: 20,
    image: friesImg,
    available: true,
  },
  {
    id: "ex-thousand",
    categoryId: "extras",
    nameAr: "١٠٠٠ جزيرة",
    nameEn: "1000 Island",
    descAr: "صوص ١٠٠٠ جزيرة.",
    descEn: "1000 Island sauce.",
    price: 20,
    image: friesImg,
    available: true,
  },

  // ─── KIDS MEALS ────────────────────────────────────────────────
  {
    id: "kids-beef",
    categoryId: "kids",
    nameAr: "وجبة أطفال بيف برجر",
    nameEn: "Kids Beef Burger Meal",
    descAr: "عيش كايزر + برجر بيف فريش + خس + مايونيز + صوص شيدر + صوص تكساس + عصير.",
    descEn: "Kaiser bun, fresh beef burger, lettuce, mayo, cheddar sauce, Texas sauce, and juice.",
    price: 100,
    image: burgerImg,
    available: true,
  },
  {
    id: "kids-fried",
    categoryId: "kids",
    nameAr: "وجبة أطفال فرايد تشيكن",
    nameEn: "Kids Fried Chicken Meal",
    descAr: "عيش كايزر + صدر دجاج مقلي + خس + مايونيز + صوص شيدر + صوص تكساس + عصير.",
    descEn: "Kaiser bun, fried chicken breast, lettuce, mayo, cheddar sauce, Texas sauce, and juice.",
    price: 100,
    image: chickenImg,
    available: true,
  },
  {
    id: "kids-chicken-burger",
    categoryId: "kids",
    nameAr: "وجبة أطفال تشيكن برجر",
    nameEn: "Kids Chicken Burger Meal",
    descAr: "عيش كايزر + تشيكن برجر + خس + مايونيز + صوص شيدر + صوص تكساس + عصير.",
    descEn: "Kaiser bun, chicken burger, lettuce, mayo, cheddar sauce, Texas sauce, and juice.",
    price: 100,
    image: chickenImg,
    available: true,
  },
];

/** Featured from the printed "جرب الجديد" section — real menu items. */
export const offers: Offer[] = [
  {
    id: "o-pasta",
    titleAr: "باستا برجر",
    titleEn: "Pasta Burger",
    descAr: "من قسم الجديد في منيو عمرانكو.",
    descEn: "From OMRANCO new items.",
    price: 150,
    badgeAr: "جرب الجديد",
    badgeEn: "Try the new",
    image: mealImg,
  },
  {
    id: "o-mix",
    titleAr: "عمرانكو مكس",
    titleEn: "Omranco Mix",
    descAr: "مكس عمرانكو.",
    descEn: "Omranco mix.",
    price: 210,
    badgeAr: "مكس",
    badgeEn: "Mix",
    image: mealImg,
  },
  {
    id: "o-kids",
    titleAr: "وجبات أطفال",
    titleEn: "Kids Meals",
    descAr: "بيف أو فرايد تشيكن أو تشيكن برجر.",
    descEn: "Beef, fried chicken or chicken burger.",
    price: 100,
    badgeAr: "١٠٠ جنيه",
    badgeEn: "100 EGP",
    image: burgerImg,
  },
];

export const branches: Branch[] = [
  {
    id: "b1",
    nameAr: "فرع حي الجامعة",
    nameEn: "Hay El Gamaa Branch",
    addressAr: "حي الجامعة، بجوار وكالة أبو راية، المنصورة",
    addressEn: "Hay El Gamaa, next to Abu Raya agency, Mansoura",
    phone: "01555218182",
    whatsapp: "201555218182",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=حي+الجامعة+المنصورة",
  },
  {
    id: "b2",
    nameAr: "فرع شارع النخلة",
    nameEn: "El Nakhla Street Branch",
    addressAr: "شارع النخلة، خلف محطة الغاز، المنصورة",
    addressEn: "El Nakhla Street, behind the gas station, Mansoura",
    phone: "0502242474",
    mapUrl: "https://www.google.com/maps/search/?api=1&query=شارع+النخلة+المنصورة",
  },
];

export const getProduct = (id: string) => products.find((p) => p.id === id);

export const CATEGORY_IDS = categories.map((c) => c.id);
